-- ============================================================
-- Project 5: Pay Equity Analysis Dashboard
-- SQL Queries — Pay Equity Audit
--
-- Research foundation:
--   Mercer Global Pay Equity Report
--     Unadjusted gender pay gap ~18% globally. Adjusted gap (controlling
--     for grade, function, location) narrows to 2-3%.
--
--   Willis Towers Watson Pay Equity Audit Framework
--     Three-stage methodology: job architecture, market pricing, regression.
--     Compa-ratio (actual / midpoint) is the primary equity metric.
--     Target band: 0.85-1.15. Below 0.90 triggers corrective review.
--
-- Compatible with: PostgreSQL 13+
-- Source table:    pay_equity_data
-- Generated by:    pay_equity_generator.py
-- ============================================================


-- ============================================================
-- QUERY 1: UNADJUSTED PAY GAP BY GENDER
-- Raw average salary difference — no controls applied.
-- Mercer benchmark: ~18% unadjusted global gender gap.
-- This is the headline number before audit adjustments.
-- ============================================================

SELECT
    gender,
    COUNT(*)                        AS headcount,
    ROUND(AVG(base_salary), 0)      AS avg_base_salary,
    ROUND(AVG(total_comp), 0)       AS avg_total_comp,
    ROUND(AVG(compa_ratio), 4)      AS avg_compa_ratio,
    ROUND(AVG(last_increase_pct), 2) AS avg_last_increase_pct
FROM pay_equity_data
GROUP BY gender
ORDER BY avg_base_salary DESC;


-- ============================================================
-- QUERY 2: UNADJUSTED GENDER PAY GAP AS A PERCENTAGE
-- Calculates the raw gap relative to male average salary.
-- Used for the executive summary KPI card.
-- ============================================================

WITH gender_avg AS (
    SELECT
        gender,
        AVG(base_salary) AS avg_salary
    FROM pay_equity_data
    GROUP BY gender
),
male_benchmark AS (
    SELECT avg_salary AS male_salary
    FROM gender_avg
    WHERE gender = 'Male'
)
SELECT
    g.gender,
    ROUND(g.avg_salary, 0)                                              AS avg_salary,
    ROUND(
        (m.male_salary - g.avg_salary) / m.male_salary * 100, 2
    )                                                                   AS pay_gap_pct
FROM gender_avg g
CROSS JOIN male_benchmark m
ORDER BY pay_gap_pct DESC;


-- ============================================================
-- QUERY 3: ADJUSTED PAY GAP — WITHIN GRADE AND DEPARTMENT
-- Controls for job grade and department (WTW audit methodology).
-- Isolates the direct pay discrimination component.
-- Mercer finding: adjusted gap should be 2-3% if job architecture is sound.
-- Any cohort exceeding 5% adjusted gap is a remediation priority.
-- ============================================================

WITH grade_dept_summary AS (
    SELECT
        job_grade,
        department,
        gender,
        COUNT(*)                        AS headcount,
        ROUND(AVG(base_salary), 0)      AS avg_salary,
        ROUND(AVG(compa_ratio), 4)      AS avg_compa_ratio
    FROM pay_equity_data
    GROUP BY job_grade, department, gender
),
male_reference AS (
    SELECT
        job_grade,
        department,
        avg_salary  AS male_avg_salary,
        avg_compa_ratio AS male_avg_compa
    FROM grade_dept_summary
    WHERE gender = 'Male'
)
SELECT
    gds.job_grade,
    gds.department,
    gds.gender,
    gds.headcount,
    gds.avg_salary,
    gds.avg_compa_ratio,
    mr.male_avg_salary,
    mr.male_avg_compa                                                           AS male_avg_compa_ratio,
    ROUND(
        (mr.male_avg_salary - gds.avg_salary) / NULLIF(mr.male_avg_salary, 0) * 100,
        2
    )                                                                           AS within_grade_gap_pct
FROM grade_dept_summary gds
LEFT JOIN male_reference mr
    ON  gds.job_grade  = mr.job_grade
    AND gds.department = mr.department
WHERE gds.gender != 'Male'
ORDER BY ABS(within_grade_gap_pct) DESC NULLS LAST;


-- ============================================================
-- QUERY 4: COMPA-RATIO ANALYSIS BY GENDER AND ETHNICITY
-- WTW framework: compa-ratio = actual salary / range midpoint.
-- Target: 0.85-1.15. Below 0.90 = underpaid risk, above 1.15 = overpaid risk.
-- ============================================================

SELECT
    gender,
    ethnicity,
    COUNT(*)                                                        AS headcount,
    ROUND(AVG(compa_ratio), 4)                                      AS avg_compa_ratio,
    ROUND(MIN(compa_ratio), 4)                                      AS min_compa_ratio,
    ROUND(MAX(compa_ratio), 4)                                      AS max_compa_ratio,
    ROUND(
        PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY compa_ratio),
        4
    )                                                               AS median_compa_ratio,
    COUNT(*) FILTER (WHERE compa_ratio < 0.90)                      AS count_below_090,
    ROUND(
        COUNT(*) FILTER (WHERE compa_ratio < 0.90) * 100.0
        / COUNT(*),
        1
    )                                                               AS pct_below_090
FROM pay_equity_data
GROUP BY gender, ethnicity
ORDER BY avg_compa_ratio ASC;


-- ============================================================
-- QUERY 5: GRADE DISTRIBUTION BY GENDER
-- Surfaces structural placement inequity.
-- WTW finding: ~66% of total pay gap is explained by grade clustering.
-- Women and URM employees concentrated in G1-G3 is the primary signal.
-- ============================================================

SELECT
    job_grade,
    job_level,
    gender,
    COUNT(*)                                            AS headcount,
    ROUND(
        COUNT(*) * 100.0
        / SUM(COUNT(*)) OVER (PARTITION BY gender),
        1
    )                                                   AS pct_within_gender,
    ROUND(
        COUNT(*) * 100.0
        / SUM(COUNT(*)) OVER (PARTITION BY job_grade),
        1
    )                                                   AS pct_within_grade
FROM pay_equity_data
GROUP BY job_grade, job_level, gender
ORDER BY job_grade, gender;


-- ============================================================
-- QUERY 6: PAY BAND COMPLIANCE BY DEPARTMENT AND GRADE
-- Employees outside their grade pay band are a pay equity risk.
-- WTW recommends corrective review for any employee below range_min.
-- ============================================================

SELECT
    department,
    job_grade,
    COUNT(*)                                                AS headcount,
    SUM(in_band_flag)                                       AS in_band_count,
    COUNT(*) - SUM(in_band_flag)                            AS out_of_band_count,
    ROUND(SUM(in_band_flag) * 100.0 / COUNT(*), 1)          AS in_band_pct,
    ROUND(AVG(range_penetration), 4)                        AS avg_range_penetration,
    ROUND(AVG(compa_ratio), 4)                              AS avg_compa_ratio
FROM pay_equity_data
GROUP BY department, job_grade
ORDER BY department, job_grade;


-- ============================================================
-- QUERY 7: INDIVIDUAL PAY EQUITY RISK FLAGS
-- Identifies employees with compa-ratio below 0.90 in cohorts
-- where male peers average above 1.00. These are the individuals
-- most likely to require remediation in a formal pay equity audit.
-- ============================================================

WITH male_cohort_avg AS (
    SELECT
        job_grade,
        department,
        AVG(compa_ratio)    AS male_avg_compa,
        AVG(base_salary)    AS male_avg_salary
    FROM pay_equity_data
    WHERE gender = 'Male'
    GROUP BY job_grade, department
)
SELECT
    p.employee_id,
    p.gender,
    p.ethnicity,
    p.department,
    p.job_grade,
    p.job_level,
    p.base_salary,
    p.range_mid,
    ROUND(p.compa_ratio, 4)                             AS compa_ratio,
    ROUND(m.male_avg_compa, 4)                          AS male_cohort_avg_compa,
    ROUND(m.male_avg_compa - p.compa_ratio, 4)          AS compa_gap,
    ROUND((m.male_avg_salary - p.base_salary), 0)       AS salary_gap_to_male_avg
FROM pay_equity_data p
JOIN male_cohort_avg m
    ON  p.job_grade  = m.job_grade
    AND p.department = m.department
WHERE p.compa_ratio < 0.90
  AND p.gender != 'Male'
  AND m.male_avg_compa > 1.00
ORDER BY compa_gap DESC;


-- ============================================================
-- QUERY 8: PROMOTION RATE BY GENDER AND GRADE
-- Promotion inequity is a leading indicator of future pay gaps.
-- Mercer research shows a 10% lower promotion rate at G3/G4 for
-- women compounds over a 5-year period into a 12-15% salary gap.
-- ============================================================

SELECT
    job_grade,
    gender,
    COUNT(*)                                                AS headcount,
    SUM(promoted_last_2yr)                                  AS promoted_count,
    ROUND(SUM(promoted_last_2yr) * 100.0 / COUNT(*), 1)    AS promotion_rate_pct,
    ROUND(AVG(base_salary), 0)                              AS avg_base_salary,
    ROUND(AVG(compa_ratio), 4)                              AS avg_compa_ratio
FROM pay_equity_data
GROUP BY job_grade, gender
ORDER BY job_grade, gender;


-- ============================================================
-- QUERY 9: MERIT INCREASE BY GENDER CONTROLLING FOR PERFORMANCE
-- Isolates gender bias in merit increase decisions by holding
-- performance rating constant. If female employees at rating 4
-- receive lower increases than male employees at rating 4,
-- the merit process itself carries a bias signal.
-- ============================================================

SELECT
    gender,
    performance_rating,
    COUNT(*)                                        AS headcount,
    ROUND(AVG(last_increase_pct), 2)                AS avg_increase_pct,
    ROUND(AVG(base_salary), 0)                      AS avg_base_salary,
    ROUND(AVG(compa_ratio), 4)                      AS avg_compa_ratio
FROM pay_equity_data
GROUP BY gender, performance_rating
ORDER BY performance_rating DESC, gender;


-- ============================================================
-- QUERY 10: EXECUTIVE SUMMARY SCORECARD
-- Single-row audit summary for the Power BI KPI page.
-- Produces all headline numbers in one query.
-- ============================================================

WITH aggregated AS (
    SELECT
        AVG(base_salary) FILTER (WHERE gender = 'Male')             AS male_avg_salary,
        AVG(base_salary) FILTER (WHERE gender = 'Female')           AS female_avg_salary,
        AVG(compa_ratio) FILTER (WHERE gender = 'Male')             AS male_avg_compa,
        AVG(compa_ratio) FILTER (WHERE gender = 'Female')           AS female_avg_compa,
        AVG(in_band_flag)                                           AS in_band_rate,
        COUNT(*) FILTER (WHERE compa_ratio < 0.85)                  AS critical_outlier_count,
        COUNT(*) FILTER (
            WHERE compa_ratio < 0.90 AND gender = 'Female'
        )                                                           AS female_below_090,
        COUNT(*)                                                     AS total_headcount,
        AVG(promoted_last_2yr) FILTER (WHERE gender = 'Male')       AS male_promo_rate,
        AVG(promoted_last_2yr) FILTER (WHERE gender = 'Female')     AS female_promo_rate
    FROM pay_equity_data
)
SELECT
    total_headcount,
    ROUND(male_avg_salary, 0)                                       AS male_avg_salary,
    ROUND(female_avg_salary, 0)                                     AS female_avg_salary,
    ROUND(
        (male_avg_salary - female_avg_salary) / male_avg_salary * 100,
        1
    )                                                               AS unadjusted_gender_gap_pct,
    ROUND(male_avg_compa, 4)                                        AS male_avg_compa_ratio,
    ROUND(female_avg_compa, 4)                                      AS female_avg_compa_ratio,
    ROUND(male_avg_compa - female_avg_compa, 4)                     AS compa_ratio_gap,
    ROUND(in_band_rate * 100, 1)                                    AS pct_in_band,
    critical_outlier_count,
    female_below_090,
    ROUND(male_promo_rate * 100, 1)                                 AS male_promotion_rate_pct,
    ROUND(female_promo_rate * 100, 1)                               AS female_promotion_rate_pct
FROM aggregated;
